[colors]
background = #000000
foreground = #ffffff
primary = #fc00ef
alert = #f53c3c
charging = #26a65b

[bar/main]
monitor = ${env:MONITOR:}
width = 100%
height = 24pt
background = ${colors.background}
foreground = ${colors.foreground}
fixed-center = true
padding-left = 0
padding-right = 0
module-margin = 0
line-size = 10
padding-top = 0
padding-bottom = 0
font-0 = "terminus-font:bold:size=18;2"
font-1 = "Symbols Nerd Font:size=12;3"
modules-left = launcher sep3 xwindow 
modules-center =  sep2 time sep date sep
#modules-right = tray sep power sep kolor sep blue sep wifi sep bg sep gromkost sep stol sep xkeyboard sep battery sep date sep time sep1
modules-right = tray sep stol sep xkeyboard sep battery sep wifi sep bg sep gromkost sep kolor sep blue sep power
cursor-click = pointer
cursor-scroll = ns-resize
wm-restack = bspwm

[module/launcher]
type = custom/text
format = " "
click-left = rofi -show drun -show-icons

[module/xwindow]
type = internal/xwindow
label = %title:0:75:…%
click-left = rofi -show window -show-icons -window-format "{w}  {t}"

[module/tray]
type = internal/tray
tray-spacing = 15px
tray-size = 18px

[module/time]
type = internal/date
interval = 30
time = %H:%M
time-alt = %I:%M %p
label = %time%

[module/date]
type        = custom/script
exec        = ~/.config/polybar/scripts/date.sh loop
interval    = 0
tail        = true
click-left  = ~/.config/polybar/scripts/date.sh toggle

[module/stol]
type        = custom/script
exec        = bash ~/.config/polybar/scripts/stol.sh loop
interval    = 0
tail        = true
click-left  = bash ~/.config/polybar/scripts/stol.sh toggle

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
format = <label-layout>
label-layout = %icon%
layout-icon-0 = us;ENG
layout-icon-1 = ru;РУС

[module/battery]
type       = custom/script
exec       = bash ~/.config/polybar/scripts/battery.sh loop
interval   = 0
tail       = true
click-left = bash ~/.config/polybar/scripts/battery.sh toggle

[module/wifi]
type = custom/text
format = ""
click-left = /usr/local/bin/odjk-wifi

[module/bg]
type = custom/text
format = ""
click-left = xterm -T "RpkocTb" -e brightness

[module/gromkost]
type = custom/text
format = ""
click-left = pavucontrol

[module/kolor]
type = custom/text
format = ""
click-left = ~/.config/polybar/scripts/kolor

[module/blue]
type = custom/text
format = "󰂯"
click-left = /usr/local/bin/odjk-blue

[module/power]
type = custom/text
format = "󰤆  "
click-left = ~/.config/rofi/rofi-power.sh

[module/sep]
type = custom/text
content = "%{B-}%{O8.5}%{B#48FF00}%{O3}%{B-}%{O8.5}"
content-padding = 0
margin = 0
content-margin = 5pt

[module/sep1]
type = custom/text
content = "%{O3}"
content-padding = 0
margin = 0
content-margin = 3pt

[module/sep2]
type = custom/text
content = "%{B-}%{O-6}%{B#48FF00}%{O3}%{B-}%{O5}"
content-padding = 0
margin = 0
content-margin = 5pt

[module/sep3]
type = custom/text
content = "%{B-}%{O4}%{B#48FF00}%{O3}%{B-}%{O4}"
content-padding = 0
margin = 0
content-margin = 5pt
